In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

current_dir = os.getcwd()
parent_dir = os.path.dirname(current_dir)

print(parent_dir)
os.chdir(parent_dir)
print(os.getcwd())

C:\Users\karan\OneDrive\Desktop\College_Stuff\ds_ml\ds3001
C:\Users\karan\OneDrive\Desktop\College_Stuff\ds_ml\ds3001

In [3]:
folder_path = './data'

file_names = []
for item in os.listdir(folder_path):
    item_path = os.path.join(folder_path, item)
    if os.path.isfile(item_path):
        file_names.append(item)

print(len(file_names))
# print(file_names)

4449

In [4]:
df = pd.DataFrame()

for name in file_names:
    path_name = './data/'+ name

    # print(path_name)

    temp_df = pd.read_csv(path_name)
    
    temp_df.drop(columns=['Unnamed: 0', 'Unnamed: 0.1', 'Unnamed: 0.1.1'], inplace=True)
    
    
    df = pd.concat([df, temp_df], ignore_index=True)

In [5]:
    
df['year'] = df['match_id'].str[:4].astype(int)
    

def update_year(row):
    if row['year'] == 2020 and int(row['match_id'][4:6]) >= 12:
        return row['year'] + 1
    elif row['year'] != 2020 and 9 <= int(row['match_id'][4:6]) <= 12:
        return row['year'] + 1
    else:
        return row['year']
    

df['year'] = df.apply(update_year, axis=1)

In [6]:
# Cleaning to make sure everything is a number

def quarter_to_int(quarter):
    return int(quarter[0])

def time_remaining_to_seconds(time_remaining):
    minutes, seconds = time_remaining.split(":")
    return float(minutes) * 60 + float(seconds)

def total_time_remaining(quarter, time):
    return (4 - quarter) * 12 * 60 + time

# Make quarter an integer
df["quarter"] = df["quarter"].apply(quarter_to_int)

# Make time_remaining a float
df["time_remaining"] = df["time_remaining"].apply(time_remaining_to_seconds)

# Create a total_time_remaining column representing time left in the game (not just the quarter)
df["total_time_remaining"] = df.apply(lambda x: total_time_remaining(x["quarter"], x["time_remaining"]), axis=1)

# Create two columns for shooting team score and opposing team score
df["shooting_team_score"] = df["score"].apply(lambda x: int(x.split("-")[0]))
df["opposing_team_score"] = df["score"].apply(lambda x: int(x.split("-")[1]))

# Create a column for score difference: shooting team score - opposing team score
df["score_difference"] = df["shooting_team_score"] - df["opposing_team_score"]

# Create a points column for number of points scored on the play if made
df["points"] = df["shot_type"].apply(lambda x: int(x.split("-")[0]))

# Sort the data by match_id and total_time_remaining (will put them in chronological order)
df = df.sort_values(["match_id", "total_time_remaining"], ascending=[True, False])

print(df.dtypes)
df.head()

match_id                 object
shotX                   float64
shotY                   float64
quarter                   int64
time_remaining          float64
player                   object
team                     object
made                       bool
shot_type                object
distance                  int64
score                    object
opp                      object
status                   object
year                      int64
total_time_remaining    float64
shooting_team_score       int64
opposing_team_score       int64
score_difference          int64
points                    int64
dtype: object

,match_id,shotX,shotY,quarter,time_remaining,player,team,made,shot_type,distance,score,opp,status,year,total_time_remaining,shooting_team_score,opposing_team_score,score_difference,points
62,200010310ATL,31.7,6.5,1,707.0,Jim Jackson,ATL,False,2-pointer,8,0-0,'CHH',tied,2001,2867.0,0,0,0,2
63,200010310ATL,24.0,5.0,1,706.0,Hanno Möttölä,ATL,True,2-pointer,0,2-0,'CHH',leads,2001,2866.0,2,0,2,2
0,200010310ATL,8.3,20.2,1,689.0,Baron Davis,CHH,False,2-pointer,22,0-2,'CHH',trails,2001,2849.0,0,2,-2,2
64,200010310ATL,14.6,8.0,1,670.0,Alan Henderson,ATL,False,2-pointer,10,2-0,'CHH',leads,2001,2830.0,2,0,2,2
1,200010310ATL,35.9,15.8,1,641.0,Jamal Mashburn,CHH,False,2-pointer,16,0-2,'CHH',trails,2001,2801.0,0,2,-2,2

In [7]:
# Everything else seems clean, so after adding a year variable to show the season it takes place, nothing else is needed

In [8]:
df.head()

,match_id,shotX,shotY,quarter,time_remaining,player,team,made,shot_type,distance,score,opp,status,year,total_time_remaining,shooting_team_score,opposing_team_score,score_difference,points
62,200010310ATL,31.7,6.5,1,707.0,Jim Jackson,ATL,False,2-pointer,8,0-0,'CHH',tied,2001,2867.0,0,0,0,2
63,200010310ATL,24.0,5.0,1,706.0,Hanno Möttölä,ATL,True,2-pointer,0,2-0,'CHH',leads,2001,2866.0,2,0,2,2
0,200010310ATL,8.3,20.2,1,689.0,Baron Davis,CHH,False,2-pointer,22,0-2,'CHH',trails,2001,2849.0,0,2,-2,2
64,200010310ATL,14.6,8.0,1,670.0,Alan Henderson,ATL,False,2-pointer,10,2-0,'CHH',leads,2001,2830.0,2,0,2,2
1,200010310ATL,35.9,15.8,1,641.0,Jamal Mashburn,CHH,False,2-pointer,16,0-2,'CHH',trails,2001,2801.0,0,2,-2,2

In [9]:
years_list = df['year'].unique()

for year in years_list:
    #print(year)
    df[df['year'] == year].to_csv('data_by_season/nba_shot_data_' + (str)(year) + '.csv', index=False)

1. What is in your data? \
   The data that is being looked at is NBA shot data from the 2001 season to 2022. It contains information about where the shot is located (both the x and y cordinate), time is happened (quarter, time in quarter), the score of the game, and who shot it. 
    

2. How will these data be useful for studying the phenomenon you're interested in? \

   This data will be useful for studying how shot behavior has changed over time because we will have every shot attempt from each seasons over the past 20 years. This will help us track behavior of each season and compare. We also have other varibles like time left, and score which help us see how they change shot behavior and how that has changed over time. 

3. What are the challenges you've resolved or expect to face in using them? \

    One challenge we met is just dealing with the huge size of the data set. All of the data doesn't fit in one csv file on github due to its size. So we had to split it up into multiple different csv's which were seperated by year. Another challenge is it takes a long time to load all of the data in initially. Also, a problem we will face is overcrowding of data because of the amount of data per year.